### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by cub007** [1542050/google-drive-stream-videos#1]
hi, when i got the link and open i got an error 403,
could you fix that? thanks a lot

**Comment by 1542050** [comment]
Hi @cub007 , can you give me your link response when build my example code ?

**Comment by cub007** [comment]
@1542050 http://45.63.122.112:8000/getlink
here is my test vps and I used the link 
Example: https://drive.google.com/file/d/0B_Jvw7q9HgamQUVPODhucjZLRkU/view?usp=sharing

**Comment by 1542050** [comment]
@cub007 :D , google fixed get link now

Please see this picture below (Link redirect from drive.google.com has been blocked by google, you only use link through proxy)
![2017-03-31_2041](https://cloud.githubusercontent.com/assets/15864617/24552964/b7daad78-1652-11e7-88bc-2089da31ac75.png)

Example (about expire 2h): http://45.63.122.112:8000/videoplayback?hash=eyJjb29raWUiOlsiRFJJVkVfU1RSRUFNPUttQmprQ2piclVnOyBEb21haW49Lm1haWwuZ29vZ2xlLmNvbTsgUGF0aD0vOyBTZWN1cmU7IEh0dHBPbmx5IiwiTklEPTEwMD1VSnZYU1Z6bkUxU3IzMmZjTVJPWndJWDF5QVpBQkpBUFh4SzFOOVd1cm1wMzZaaU5HLTdrZ0wwdk93bjBaaGJZQ2NGM3g3c2szdkpCVllkSjBtRk1OTWJzS2RLQUhROWMyeERKS1E3cHg4LUw1SUtqbW5rcHB6Q3dzbUR4TjdOTjtEb21haW49Lmdvb2dsZS5jb207UGF0aD0vO0V4cGlyZXM9U2F0LCAzMC1TZXAtMjAxNyAxMzozOToyNCBHTVQ7SHR0cE9ubHkiXSwiZG9tYWluIjoiaHR0cHM6Ly9yNC0tLXNuLW9ndWVsbjd5LmMubWFpbC5nb29nbGUuY29tIn0&id=f68d8502dbaf93eb&itag=59&source=webdrive&requiressl=yes&ttl=transient&mm=30&mn=sn-ogueln7y&ms=nxu&mv=u&pl=24&ei=DFzeWJCJLpLp-gPN-KTgAg&mime=video/mp4&lmt=1474338539276409&mt=1490967309&ip=45.63.122.112&ipbits=0&expire=1490981964&cp=QVJOUkpfUFlURVhNOkdyRmdwRWp5clpj&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cttl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cmime%2Clmt%2Ccp&signature=5BA22B6DA389B8067FBA86C7AD34620495986757.AEE97CA3E3B543EAE4D99AECE303370937B4B918&key=ck2&app=explorer

**Comment by cub007** [comment]
@1542050 
but did you see this https://github.com/quocnguyen/dt-api 
duongtang.clgt.vn and api.getlinkdrive.com

those sites still work

**Comment by 1542050** [comment]
oh, i think duongtang.clgt.vn found another way, I will update this project in the next version :D

**Comment by cub007** [comment]
@1542050 LOL waitting for you
